interface ThemeColors {
    PRIMARY_BLUE: string,
    PRIMARY_BLUE_LIGHT: string,
    SUCCESS: string,
    WARNING: string,
    ERROR: string,
    BACKGROUND: string,
    CARD_BACKGROUND: string,
    BORDER_COLOR: string,
    TEXT_PRIMARY: string,
    TEXT_SECONDARY: string,
    TEXT_DISABLED: string,
    COMPLETED: string,
    INPROGRESS: string,
    PENDING: string,
    TEXT_WHITE: string,
    HIGH_PRIORITY: string,
    MEDIUM_PRIORITY: string,
    LOW_PRIORITY: string,
    WARNING_LIGHT: string,
    ERROR_LIGHT: string,
    SUCCESS_LIGHT: string,
}

export const colors: ThemeColors = {
    PRIMARY_BLUE: '#3F51B5',
    PRIMARY_BLUE_LIGHT: '#5C6BC0',
    SUCCESS: '#4CAF50',
    WARNING: '#FFC107',
    ERROR: '#FF5252',
    BACKGROUND: '#F5F7FA',
    CARD_BACKGROUND: '#FFFFFF',
    BORDER_COLOR: '#E2E8F0',
    TEXT_WHITE: '#FFFFFF',
    TEXT_PRIMARY: '#2D3748',
    TEXT_SECONDARY: '#718096',
    TEXT_DISABLED: '#A0AEC0',
    COMPLETED: '#4CAF50',
    INPROGRESS: '#3F51B5',
    PENDING: '#FFC107',
    HIGH_PRIORITY: "#FF7043",
    MEDIUM_PRIORITY: "#3F51B5",
    LOW_PRIORITY: "#4CAF50",
    WARNING_LIGHT: '#FFF3CD',
    ERROR_LIGHT: '#FDECEA',
    SUCCESS_LIGHT: '#E8F5E9',
}
